# Generated by Django 4.1.7 on 2023-03-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_fermier_motpass"),
    ]

    operations = [
        migrations.DeleteModel(
            name="fermier",
        ),
    ]
