# Generated by Django 4.1.7 on 2023-03-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0003_delete_fermier"),
    ]

    operations = [
        migrations.CreateModel(
            name="fermier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("motpass", models.CharField(max_length=50)),
            ],
        ),
    ]
