# Generated by Django 4.1.7 on 2023-04-05 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="fermier",
            new_name="superviseur",
        ),
    ]
