# Generated by Django 4.1.7 on 2023-04-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_client_supervisor_delete_superviseur_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="client_id",
        ),
        migrations.RemoveField(
            model_name="client",
            name="image",
        ),
        migrations.RemoveField(
            model_name="supervisor",
            name="supervisor_id",
        ),
    ]
