# Generated by Django 4.1.7 on 2023-04-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_remove_client_client_id_remove_client_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supervisor",
            name="image",
        ),
    ]
