# Generated by Django 4.1.7 on 2023-04-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_remove_supervisor_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="mot_pass",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="supervisor",
            name="mot_pass",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
