# Generated by Django 4.1.7 on 2023-05-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("home", "0012_customuser_remove_supervisor_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.RenameField(
            model_name="supervisor",
            old_name="mot_pass",
            new_name="password",
        ),
        migrations.AddField(
            model_name="supervisor",
            name="groups",
            field=models.ManyToManyField(
                related_name="supervisor_groups", to="auth.permission"
            ),
        ),
        migrations.AddField(
            model_name="supervisor",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="supervisor",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="supervisor",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="supervisor_user_permissions", to="auth.group"
            ),
        ),
    ]
