# Generated by Django 4.1.7 on 2023-05-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_delete_customuser_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supervisor",
            old_name="password",
            new_name="mot_pass",
        ),
        migrations.RemoveField(
            model_name="supervisor",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="supervisor",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="supervisor",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="supervisor",
            name="user_permissions",
        ),
    ]
