# Generated by Django 4.1.7 on 2023-05-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_rename_password_supervisor_mot_pass_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="supervisor",
        ),
    ]
