# Generated by Django 4.1.7 on 2023-05-03 15:17

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_remove_client_supervisor"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="supervisor",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
