# Generated by Django 4.1.7 on 2023-05-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_alter_supervisor_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="supervisor",
            managers=[],
        ),
        migrations.AddField(
            model_name="client",
            name="supervisor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.supervisor",
            ),
        ),
    ]
