# Generated by Django 4.1.7 on 2023-05-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_alter_supervisor_managers_client_supervisor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="supervisor",
        ),
    ]
