# Generated by Django 4.1.7 on 2023-05-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_remove_client_supervisor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="client",
        ),
    ]
