# Generated by Django 4.1.7 on 2023-05-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_delete_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supervisor",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
