# Generated by Django 4.1.7 on 2023-05-11 14:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, null=True)),
                ("e_mail", models.EmailField(max_length=100, null=True)),
                ("mot_pass", models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="M_polygon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=80, null=True)),
                ("cord", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="myPolygon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=80, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PolygonField(
                        null=True, srid=4326
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="project",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=100, null=True)),
                ("region", models.CharField(max_length=100, null=True)),
                (
                    "client",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="superviseur.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="point",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=80, null=True)),
                ("cord", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("référence", models.CharField(max_length=50, null=True)),
                (
                    "parcelle",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="superviseur.mypolygon",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="superviseur.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mypolygon",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="superviseur.project",
            ),
        ),
    ]
