# Generated by Django 4.1.7 on 2023-05-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superviseur", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="dat_deb",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="dat_fin",
            field=models.DateField(null=True),
        ),
    ]
