# Generated by Django 4.1.7 on 2023-05-26 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("superviseur", "0004_client_superviseur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="client",
        ),
        migrations.AddField(
            model_name="client",
            name="proj",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="superviseur.project",
            ),
        ),
    ]
