# Generated by Django 4.1.7 on 2023-05-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("superviseur", "0007_alter_project_client"),
    ]

    operations = [
        migrations.DeleteModel(
            name="M_polygon",
        ),
    ]
