# Generated by Django 4.1.7 on 2023-05-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superviseur", "0008_delete_m_polygon"),
    ]

    operations = [
        migrations.AddField(
            model_name="point",
            name="FWI",
            field=models.BigIntegerField(null=True),
        ),
    ]
