# Generated by Django 4.1.7 on 2023-05-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superviseur", "0009_point_fwi"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="wind",
            field=models.BigIntegerField(default=0),
        ),
    ]
