# Generated by Django 4.1.7 on 2023-05-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superviseur", "0010_post_wind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
