# Generated by Django 4.1.7 on 2023-05-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("superviseur", "0011_alter_post_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="published_date",
        ),
    ]
